[package]
name = "duckblog"
version = "0.1.0"
edition = "2021"
rust-version = "1.65.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio = { version = "1.25.0", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"] }
syntect = "5.0.0"
maud = "0.24.0"
chrono = "0.4.23"
toml = "0.7.2"
color-eyre = "0.6.2"
tower-http = {version ="0.3.5", features = ["fs", "trace"]}
axum-extra = {version= "0.5.0", features = ["spa"]}
tower = "0.4.13"
base64 = "0.21.0"
image = "0.24.5"
new_mime_guess = "4.0.1"
liquid = "0.26.0"