[package]
name = "duckblog"
version = "0.2.0"
edition = "2021"
rust-version = "1.65.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio = { version = "1.28.0", features = ["full"] }
serde = { version = "1.0.130", features = ["derive"] }
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"] }
syntect = "5.0.0"
chrono = "0.4.23"
toml = "0.7.2"
tower-http = {version = "0.4.0", features = ["fs", "trace"]}
axum-extra = {version= "0.5.0", features = ["spa"]}
tower = {version = "0.4.13", features = ["full"]}
base64 = "0.21.0"
image = "0.24.5"
new_mime_guess = "4.0.1"
liquid = "0.26.0"
humantime = "2.1.0"
regex = "1.8.1"
reqwest = "0.11.16"
copy_dir = "0.1.2"
itertools = "0.10.5"
opentelemetry = { version = "0.18.0", features = ["rt-tokio"]}
opentelemetry-otlp = {version = "0.11.0", features = ["tokio", "http-proto", "reqwest-client"]}
tonic = {version = "0.9.2", features = ["tls-roots"]}
color-eyre = "0.6.2"
tracing-opentelemetry = "0.18.0"
tracing-error = "0.2.0"
sentry = {version = "0.31.0", features = ["anyhow"]}
tracing-honeycomb = "0.4.3"
dotenvy = "0.15.7"
rss = "2.0.4"
