[package]
name = "duckblog"
version = "0.2.0"
edition = "2021"
rust-version = "1.70.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = { version = "1.37.0", features = ["full"] }
serde = { version = "1.0.192", features = ["derive"] }
pulldown-cmark = { version = "0.10.3"}
chrono = {version ="0.4.31", features = ["serde"]}
toml = "0.8.8"
tower-http = {version = "0.5", features = ["fs", "trace"]}
axum-extra = {version= "0.9"}
tower = {version = "0.4.13", features = ["full"]}
base64 = "0.22.1"
image = "0.25.1"
new_mime_guess = "4.0.1"
liquid = "0.26.4"
humantime = "2.1.0"
regex = "1.10.4"
reqwest = {version = "0.12.4", default-features = false, features = ["rustls-tls-native-roots"]}
copy_dir = "0.1.3"
itertools = "0.13.0"
moka = { version = "0.12.7", features = ["future"] }
opentelemetry = {version = "0.22.0" }
opentelemetry-otlp = {version = "0.15.0", features = ["tokio", "http-proto", "reqwest-client", "reqwest-rustls"]}
opentelemetry_sdk = {version = "0.22", features = ["rt-tokio"]}
color-eyre = "0.6.3"
tracing-opentelemetry = "0.23.0"
tracing-error = "0.2.0"
sentry = {version = "0.32.3", features = ["anyhow"]}
dotenvy = "0.15.7"
rss = "2.0.8"
serde_json = "1.0.117"

# Use jemalloc for static linking
[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.5.4"