[package]
name = "duckblog"
version = "0.2.5"
edition = "2021"
rust-version = "1.70.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tokio = { version = "1.39", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
pulldown-cmark = { version = "0.11.0" }
chrono = { version = "0.4.38", features = ["serde"] }
toml = "0.8"
tower-http = { version = "0.5", features = ["fs", "trace"] }
axum-extra = { version = "0.9" }
tower = { version = "0.4.13", features = ["full"] }
base64 = "0.22.1"
image = "0.25.2"
new_mime_guess = "4.0.1"
liquid = "0.26.8"
humantime = "2.1.0"
regex = "1.10.5"
reqwest = { version = "0.12.5", default-features = false, features = [
    "rustls-tls",
    "json",
] }
copy_dir = "0.1.3"
itertools = "0.13.0"
color-eyre = "0.6.3"
tracing-error = "0.2.0"
sentry = { version = "0.34", default-features = false, features = ["anyhow", "rustls", "backtrace", "reqwest", "tokio", "contexts", "panic", "debug-images"] }
dotenvy = "0.15.7"
rss = "2.0.8"
serde_json = "1.0.120"
serde_yml = "0.0.11"

# Use jemalloc for static linking
[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies.jemallocator]
version = "0.5.4"
