[package]
name = "duckblog"
version = "0.2.6"
edition = "2021"
rust-version = "1.70.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.7"
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1.41", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
pulldown-cmark = { version = "0.12" }
chrono = { version = "0.4.38", features = ["serde"] }
tower-http = { version = "0.5", features = ["fs", "trace"] }
tower = { version = "0.4.13", features = ["full"] }
liquid = "0.26"
regex = "1.11"
reqwest = { version = "0.12", default-features = false, features = [
    "rustls-tls",
    "json",
] }
copy_dir = "0.1.3"
itertools = "0.13.0"
color-eyre = "0.6.3"
sentry = { version = "0.34", default-features = false, features = ["anyhow", "rustls", "backtrace", "reqwest", "tokio", "contexts", "panic", "debug-images"] }
dotenvy = "0.15.7"
rss = "2.0.8"
serde_json = "1.0.120"
serde_yml = "0.0.12"

[profile.release]
debug = true