[package]
name = "duckblog"
version = "0.2.0"
edition = "2021"
rust-version = "1.65.0"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.4"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
tokio = { version = "1.32.0", features = ["full"] }
serde = { version = "1.0.188", features = ["derive"] }
pulldown-cmark = { version = "0.9.2", default-features = false, features = ["simd"] }
syntect = "5.0.0"
chrono = {version ="0.4.31", features = ["serde"]}
toml = "0.8.2"
tower-http = {version = "0.4.4", features = ["fs", "trace"]}
axum-extra = {version= "0.5.0", features = ["spa"]}
tower = {version = "0.4.13", features = ["full"]}
base64 = "0.21.4"
image = "0.24.5"
new_mime_guess = "4.0.1"
liquid = "0.26.0"
humantime = "2.1.0"
regex = "1.8.1"
reqwest = "0.11.22"
copy_dir = "0.1.3"
itertools = "0.11.0"
moka = { version = "0.12.1", features = ["future"] }
opentelemetry = { version = "0.18.0", features = ["rt-tokio"]}
opentelemetry-otlp = {version = "0.11.0", features = ["tokio", "http-proto", "reqwest-client"]}
tonic = {version = "0.10.1", features = ["tls-roots"]}
color-eyre = "0.6.2"
tracing-opentelemetry = "0.18.0"
axum-tracing-opentelemetry = "0.14.1"
tracing-error = "0.2.0"
sentry = {version = "0.31.7", features = ["anyhow", "tracing"]}
dotenvy = "0.15.7"
rss = "2.0.4"
sentry-tracing = "0.31.7"
serde_json = "1.0.107"
