version: '3'
services:
  duckblog:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8010:80"
    volumes:
      - .env:/duckblog/.env
      - ./static:/duckblog/static
      - ./liquid:/duckblog/liquid
      - ./content:/duckblog/content
